# Generated by Django 5.1.2 on 2024-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_slug_profile_faculty_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
