# Generated by Django 5.1.2 on 2024-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_useractivity_useractivitylab_useractivityweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chip',
            field=models.IntegerField(default=12121),
            preserve_default=False,
        ),
    ]
