# Generated by Django 5.1.2 on 2024-11-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chip',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
