# Generated by Django 5.1.2 on 2024-10-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role'),
        ),
    ]
